feat: BAL-5 importation régulière deca par api avec historisation
mission-apprentissage/bal pull request #362
Opened 2024-06-26 23:12 UTC by alanlr

Cron quotidient à 4h30 d'importation des données DECA par api
Enregistrement des modifications dans decaHistory champ par champ
Enregistrement sous forme de nouveaux contrats lorsque les modifications touchent le nom de l'alternant ou le type de contrat

2024-06-27 05:48 UTC, kevbarns commented on server/src/modules/jobs/deca/hydrate-deca.ts
> +    : (await getLastDecaCreatedDateInDb()) ?? new Date(`2024-05-21T00:00:00.000Z`);
date en dure ?

2024-06-27 05:50 UTC, kevbarns commented on server/src/modules/jobs/deca/hydrate-deca.ts
> +            ...ifDefined("type_contrat", "" + contrat.detailsContrat.typeContrat), // TDB, LBA
y'a un espace dans le champ ? pourquoi ne pas trimer dans la fonction ifDefined ou en amount plutôt ?

2024-06-27 07:17 UTC, moroine requested changes
⚠️ Le modèle a changé sans migration.

Est-ce que t'as testé les perfs ? On est sur quel volume de donné journalier ? Quel est le but du changement ici?

2024-06-27 07:17 UTC, moroine commented on server/src/modules/jobs/deca/hydrate-deca.ts
> +            oldContrat.alternant.nom !== currentContrat.alternant.nom)
Pourquoi ne pas mettre ça en plus comme condition dans le find avec un index adapté en conséquence ?

2024-06-27 07:17 UTC, moroine commented on server/src/modules/jobs/deca/hydrate-deca.ts
> +        /* decaHistory contient les modifs lorsque modif sur numéro de contrat + alternant.nom + type contrat identique */
Est-ce vrai sur le stock ? A-t-on besoin d'une migration ?

2024-06-27 07:17 UTC, moroine commented on server/src/modules/jobs/deca/hydrate-deca.ts
> +            { sort: { created_at: -1 }, upsert: true, returnDocument: "after" }
On se base vraiment sur `created_at` et pas plutot `no_contrat` + `type_contrat` + `alternant.nom` ? 

D'après le code j'ai l'impression qu'il y a unicité sur ce trio (modulo le stock a migrer).

2024-06-27 07:17 UTC, moroine commented on server/src/modules/jobs/deca/hydrate-deca.ts
> +            oldContrat.alternant.nom !== currentContrat.alternant.nom)
D'ailleurs t'as des exemples ? Comment le numéro de contrat peut rester le meme pour des noms different ? De meme pour le type de contrat ? Est-ce que ces opérations ne serait pas plutot de la correction d'erreur de saisie, auquel cas il est nécessaire de garder l'unicité par `no_contrat` ?

2024-06-27 07:17 UTC, moroine commented on server/src/modules/jobs/deca/hydrate-deca.ts
>    const lastDecaItem = await getDbCollection("deca").find().sort({ created_at: -1 }).limit(1).toArray();
Il faut un index pour ça

2024-06-27 07:17 UTC, moroine commented on server/src/modules/jobs/deca/hydrate-deca-history.ts
> +      }
UpdateOne avec upsert ?

2024-07-08 15:57 UTC, alanlr commented on server/src/modules/jobs/deca/hydrate-deca.ts
> +              ...ifDefined("date_fin_formation", contrat.formation.dateFinFormation, parseDate), // TDB
--> 2008-10-01T00:00:00.000Z

2024-07-08 17:55 UTC, kevbarns approved these changes

2024-07-09 08:09 UTC, moroine reviewed
Review partielle, je continuerais en fin d'après-midi

2024-07-09 08:24 UTC, alanlr commented on server/src/db/migrations/20240628000000-deca.ts
> +            $toString: "$alternant.sexe",
si mais le stock contient des 1 et 2 en number

2024-07-09 09:49 UTC, alanlr commented on server/src/db/migrations/20240628000000-deca.ts
> +    bypassDocumentValidation: true,
A la base j'avais trois champs dans la même aggregation. Mais c'est vrait que je peux merge avec l'update many qui commence à la ligne 34

2024-07-09 10:12 UTC, alanlr commented on server/src/modules/jobs/deca/hydrate-deca.ts
>    return value ? { [key]: transform(value) } : {};
Chacunes de ces valeurs peuvent avoir leur légitimité. 
Je crains les effets de bords.

2024-07-09 10:12 UTC, alanlr commented on server/src/modules/jobs/deca/hydrate-deca.ts
> +export const shouldStopCallingDeca = ({
oui

2024-07-09 10:15 UTC, alanlr commented on server/src/modules/jobs/deca/hydrate-deca.ts
> +  const startHour = forceStartHour ?? new Date().getHours();
> Je comprend pas le `forceStartHour` et `startHour` ?
> 
> On veut pas juste now ?

Les deux variables c'est pour ajouter des tests unitaires.

2024-07-09 12:59 UTC, moroine commented on server/src/modules/jobs/deca/hydrate-deca.ts
> +        const now = new Date(dateDebut);
Ou alors on ne se casse pas la tete et on sauvegarde `created_at` & `updated_at` en string. 

On peut meme rename en `create_date` & `updated_date`

2024-07-09 14:16 UTC, moroine requested changes
All reviewed

2024-07-09 14:16 UTC, moroine commented on server/src/modules/jobs/deca/hydrate-deca.ts
>    // Si la dernière date est plus tard qu'hier, on prend d'avant hier en date de debut de référence
C'est encore utilisé ça du coup ?

2024-07-09 14:16 UTC, moroine commented on server/src/modules/jobs/jobs.ts
> +              handler: () => hydrateDeca({ from: "", to: "" }),
Vraiment bizarre, on a besoin de ces params ?

2024-07-09 14:16 UTC, moroine commented on server/tests/unit/deca.test.ts
> +  });
Tu peux ajouter si y'a deja des jobs et avec les dates:

`{ start: new Date("2024-01-01T00:00:00.00Z"), end: new Date("2024-01-04T23:00:00.00Z") }`
`{ start: new Date("2024-07-01T00:00:00.00+02:00"), end: new Date("2024-07-04T23:00:00.00+02:00") }`

2024-07-09 14:16 UTC, moroine commented on shared/helpers/mongoSchema/__snapshots__/mongoSchemaBuilder.test.ts.snap
> -    },
Migration pour supprimer le resumeToken ?

2024-07-09 14:16 UTC, moroine commented on shared/helpers/mongoSchema/__snapshots__/mongoSchemaBuilder.test.ts.snap
> +    },
Required, besoin de migration ?

2024-07-10 12:05 UTC, alanlr commented on server/src/modules/jobs/deca/hydrate-deca.ts
> +        const now = new Date(dateDebut);
en string ca me convient très bien

2024-07-11 07:30 UTC, alanlr commented on server/src/modules/jobs/deca/hydrate-deca.ts
> +        const now = parseDate(dateDebut) as Date;
ok merci c'était exactement pour ça. je connaissais pas cette syntaxe

2024-07-12 14:29 UTC, merged